/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {LabelResponse} from '../../models/label-response';

export interface CreateLabel$Params {
      body: string
}

export function createLabel(http: HttpClient, rootUrl: string, params: CreateLabel$Params, context?: HttpContext): Observable<StrictHttpResponse<LabelResponse>> {
  const rb = new RequestBuilder(rootUrl, createLabel.PATH, 'post');
  if (params) {
    rb.body(params.body, 'text/plain');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LabelResponse>;
    })
  );
}

createLabel.PATH = '/api/v1/labels';
