/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {LabelResponse} from '../../models/label-response';

export interface GetLabels$Params {
}

export function getLabels(http: HttpClient, rootUrl: string, params?: GetLabels$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LabelResponse>>> {
  const rb = new RequestBuilder(rootUrl, getLabels.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LabelResponse>>;
    })
  );
}

getLabels.PATH = '/api/v1/labels';
