/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {DocumentSearchResponse} from '../../models/document-search-response';

export interface SearchDocuments$Params {
}

export function searchDocuments(http: HttpClient, rootUrl: string, params?: SearchDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentSearchResponse>> {
  const rb = new RequestBuilder(rootUrl, searchDocuments.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentSearchResponse>;
    })
  );
}

searchDocuments.PATH = '/api/v1/search';
