/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {DocumentResponse} from '../../models/document-response';

export interface UpdateDocumentFile$Params {
  uuid: string;
  file: Blob;
}

export function updateDocumentFile(http: HttpClient, rootUrl: string, params: UpdateDocumentFile$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, updateDocumentFile.PATH, 'post');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.query('file', params.file, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponse>;
    })
  );
}

updateDocumentFile.PATH = '/api/v1/documents/{uuid}/file';
