/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {DocumentResponse} from '../../models/document-response';
import {DocumentUpdateRequest} from '../../models/document-update-request';

export interface UpdateDocument$Params {
  uuid: string;
      body: DocumentUpdateRequest
}

export function updateDocument(http: HttpClient, rootUrl: string, params: UpdateDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, updateDocument.PATH, 'put');
  if (params) {
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponse>;
    })
  );
}

updateDocument.PATH = '/api/v1/documents/{uuid}';
