/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetDocuments$Params as GetDocuments$Params } from './fn/operations/get-documents';
export { getDocuments as getDocuments } from './fn/operations/get-documents';
export type { CreateDocument$Params as CreateDocument$Params } from './fn/operations/create-document';
export { createDocument as createDocument } from './fn/operations/create-document';
export type { GetDocument$Params as GetDocument$Params } from './fn/operations/get-document';
export { getDocument as getDocument } from './fn/operations/get-document';
export type { UpdateDocument$Params as UpdateDocument$Params } from './fn/operations/update-document';
export { updateDocument as updateDocument } from './fn/operations/update-document';
export type { DeleteDocument$Params as DeleteDocument$Params } from './fn/operations/delete-document';
export { deleteDocument as deleteDocument } from './fn/operations/delete-document';
export type { GetDocumentFile$Params as GetDocumentFile$Params } from './fn/operations/get-document-file';
export { getDocumentFile as getDocumentFile } from './fn/operations/get-document-file';
export type { UpdateDocumentFile$Params as UpdateDocumentFile$Params } from './fn/operations/update-document-file';
export { updateDocumentFile as updateDocumentFile } from './fn/operations/update-document-file';
export type { GetLabels$Params as GetLabels$Params } from './fn/operations/get-labels';
export { getLabels as getLabels } from './fn/operations/get-labels';
export type { CreateLabel$Params as CreateLabel$Params } from './fn/operations/create-label';
export { createLabel as createLabel } from './fn/operations/create-label';
export type { GetLabel$Params as GetLabel$Params } from './fn/operations/get-label';
export { getLabel as getLabel } from './fn/operations/get-label';
export type { UpdateLabel$Params as UpdateLabel$Params } from './fn/operations/update-label';
export { updateLabel as updateLabel } from './fn/operations/update-label';
export type { DeleteLabel$Params as DeleteLabel$Params } from './fn/operations/delete-label';
export { deleteLabel as deleteLabel } from './fn/operations/delete-label';
export type { GetDocumentsWithLabel$Params as GetDocumentsWithLabel$Params } from './fn/operations/get-documents-with-label';
export { getDocumentsWithLabel as getDocumentsWithLabel } from './fn/operations/get-documents-with-label';
export type { SearchDocuments$Params as SearchDocuments$Params } from './fn/operations/search-documents';
export { searchDocuments as searchDocuments } from './fn/operations/search-documents';
