/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { DocumentResponse } from './models/document-response';
export type { DocumentSearchResponse } from './models/document-search-response';
export type { DocumentUpdateRequest } from './models/document-update-request';
export type { LabelModel } from './models/label-model';
export type { LabelResponse } from './models/label-response';
export type { SearchPagingResponse } from './models/search-paging-response';
