/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {LabelModel} from '../models/label-model';

export interface DocumentResponse {
  labels?: Array<LabelModel> | null;
  name?: string | null;
  uuid?: string | null;
}
