/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {DocumentResponse} from '../models/document-response';
import {SearchPagingResponse} from '../models/search-paging-response';

export interface DocumentSearchResponse {
  list?: Array<DocumentResponse> | null;
  paging?: SearchPagingResponse;
}
