CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE document_entity
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_documententity PRIMARY KEY (id)
);

CREATE TABLE document_entity_labels
(
    documents_id INTEGER NOT NULL,
    labels_id    INTEGER NOT NULL
);

CREATE TABLE label_entity
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_labelentity PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

ALTER TABLE label_entity
    ADD CONSTRAINT uc_labelentity_name UNIQUE (name);

ALTER TABLE document_entity_labels
    ADD CONSTRAINT fk_docentlab_on_document_entity FOREIGN KEY (documents_id) REFERENCES document_entity (id);

ALTER TABLE document_entity_labels
    ADD CONSTRAINT fk_docentlab_on_label_entity FOREIGN KEY (labels_id) REFERENCES label_entity (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);