CREATE TABLE documents
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    file_url VARCHAR(255),
    CONSTRAINT pk_documents PRIMARY KEY (id)
);

CREATE TABLE documents_labels
(
    documents_id INTEGER NOT NULL,
    labels_id    INTEGER NOT NULL
);

CREATE TABLE labels
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_labels PRIMARY KEY (id)
);

ALTER TABLE labels
    ADD CONSTRAINT uc_labels_name UNIQUE (name);

ALTER TABLE documents_labels
    ADD CONSTRAINT fk_docentlab_on_documents FOREIGN KEY (documents_id) REFERENCES documents (id);

ALTER TABLE documents_labels
    ADD CONSTRAINT fk_docentlab_on_labels FOREIGN KEY (labels_id) REFERENCES labels (id);
