openapi: "3.1.0"
info:
  title: "swen3_paperless API"
  description: "swen3_paperless API"
  version: "1.0.0"
servers:
  - url: "https://swen3_paperless"
paths:
  /api/v1/documents:
    get:
      summary: "GET api/v1/documents"
      operationId: "getDocuments"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DocumentResponse"
    post:
      summary: "POST api/v1/documents"
      operationId: "createDocument"
      parameters:
        - name: "file"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "binary"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
  /api/v1/documents/{uuid}:
    get:
      summary: "GET api/v1/documents/{uuid}"
      operationId: "getDocument"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
    put:
      summary: "PUT api/v1/documents/{uuid}"
      operationId: "updateDocument"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentUpdateRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
    delete:
      summary: "DELETE api/v1/documents/{uuid}"
      operationId: "deleteDocument"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
  /api/v1/documents/{uuid}/file:
    get:
      summary: "GET api/v1/documents/{uuid}/file"
      operationId: "getDocumentFile"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST api/v1/documents/{uuid}/file"
      operationId: "updateDocumentFile"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "file"
          in: "query"
          required: true
          schema:
            type: "string"
            format: "binary"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
  /api/v1/labels:
    get:
      summary: "GET api/v1/labels"
      operationId: "getLabels"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/LabelResponse"
    post:
      summary: "POST api/v1/labels"
      operationId: "createLabel"
      requestBody:
        content:
          text/plain:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LabelResponse"
  /api/v1/labels/{uuid}:
    get:
      summary: "GET api/v1/labels/{uuid}"
      operationId: "getLabel"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LabelResponse"
    put:
      summary: "PUT api/v1/labels/{uuid}"
      operationId: "updateLabel"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        content:
          text/plain:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LabelResponse"
    delete:
      summary: "DELETE api/v1/labels/{uuid}"
      operationId: "deleteLabel"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
  /api/v1/labels/{uuid}/documents:
    get:
      summary: "GET api/v1/labels/{uuid}/documents"
      operationId: "getDocumentsWithLabel"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DocumentResponse"
  /api/v1/search:
    post:
      summary: "POST api/v1/search"
      operationId: "searchDocuments"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DocumentSearchResponse"
components:
  schemas:
    LabelModel:
      type: "object"
      properties:
        uuid:
          type: "string"
          format: "uuid"
          nullable: true
        name:
          type: "string"
          nullable: true
    DocumentResponse:
      type: "object"
      properties:
        uuid:
          type: "string"
          nullable: true
        name:
          type: "string"
          nullable: true
        labels:
          type: "array"
          nullable: true
          items:
            $ref: "#/components/schemas/LabelModel"
    DocumentUpdateRequest:
      type: "object"
      properties:
        name:
          type: "string"
          nullable: true
        labels:
          type: "array"
          nullable: true
          items:
            type: "string"
    LabelResponse:
      type: "object"
      properties:
        uuid:
          type: "string"
          nullable: true
        name:
          type: "string"
          nullable: true
    SearchPagingResponse:
      type: "object"
      properties:
        currentCount:
          type: "integer"
          format: "int32"
          nullable: true
        maxCount:
          type: "integer"
          format: "int32"
          nullable: true
    DocumentSearchResponse:
      type: "object"
      properties:
        list:
          type: "array"
          nullable: true
          items:
            $ref: "#/components/schemas/DocumentResponse"
        paging:
          nullable: true
          $ref: "#/components/schemas/SearchPagingResponse"