# Properties for the Dev-Environment
# DB Configuration
DATABASE_URL=jdbc:postgresql://localhost:5432/paperless
spring.datasource.url=${DATABASE_URL}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.password=paperless
spring.datasource.username=paperless
# other Properties