# Template-Properties-File for the local-configuration
# this file should not contain with valid values
# copy this file and remove "template-" from the start of the file before adding the required properties
